import { PRODUCT_ENRICHMENTS } from "./product-enrichments";

export const COMPANY_INFO = {
  name: "Axis Packaging",
  tagline: "Your Box, Your Brand",
  phone: "+447367066309",
  email: "info@theaxispackaging.com",
  address: "104 Pudsey Road, Leeds, LS12 3TZ, United Kingdom.",
  hours: "Mon-Fri: 8AM-6PM PST",
};

export const NAVIGATION_ITEMS = [
  { name: "Home", href: "/" },
  { name: "Products", href: "/products" },
  { name: "Industries", href: "/industries" },
  { name: "Blog", href: "/blog" },
  { name: "Sustainability", href: "/sustainability" },
];

const _PRODUCT_CATEGORIES = [
  {
    name: "Custom Folding Carton Boxes",
    description: "Get custom folding carton boxes with flexible sizes, fast production, and high quality perfect for retail, gifting, and more.",
    icon: "📦",
    image: "/assets/packify-custom-boxes.png",
    slug: "folding-carton-boxes",
    metaTitle: "Premium and Customized Folding Carton Boxes - Axis Packaging",
    metaDescription: "Get custom folding carton boxes with fast turnaround, fast production, and high quality perfect for retail, gifting, and more.",
    h1: "Custom Folding Carton Boxes for Premium Packaging",
    alt: "folding carton boxes",
  },
  {
    name: "Premium Rigid Boxes",
    description: "Shop rigid boxes for premium products. Custom sizes, luxury finishes, and eco-friendly packaging with fast flip turnaround.",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "rigid-boxes",
    metaTitle: "Buy Custom Rigid Boxes - Premium Packaging - Axis Packaging",
    metaDescription: "Shop rigid boxes for premium products. Custom sizes, luxury finishes, and eco-friendly packaging with fast flip turnaround.",
    h1: "Custom & Premium Rigid Boxes",
    alt: "Custom rigid box with luxury finish,Premium rigid gift boxes",
  },
  {
    name: "Custom Box Inserts",
    description: "Get custom box inserts for gifts and retail. Durable, stylish and versatile packaging solutions with rapid turnaround.",
    icon: "📋",
    image: "/assets/Custom Box Inserts.jpg",
    slug: "box-inserts",
    metaTitle: "Buy Custom Box Inserts - Premium Packaging - Axis Packaging",
    metaDescription: "Get custom box inserts for gifts and retail. Durable, stylish and versatile packaging solutions with rapid turnaround.",
    h1: "Custom & Premium Box Inserts for Packaging",
    alt: "Custom box inserts,Premium packaging inserts",
  },
  {
    name: "Custom Reusable Bags",
    description: "Looking for sustainable packaging? Our custom reusable bags offer strength, style, and sustainability. Ideal for retail, grocery, and promotions.",
    icon: "👜",
    image: "/assets/packify-retail-packaging.png",
    slug: "reusable-bags",
    metaTitle: "Buy Custom Reusable Bags - Top Durable & Shopping Bags",
    metaDescription: "Looking for sustainable packaging? Our custom reusable bags offer strength, style, and sustainability. Ideal for retail, grocery, and promotions.",
    h1: "Custom & Eco-Friendly Reusable Bags",
    alt: "custom reusable bags,",
  },
  {
    name: "Printed Mailer Bags",
    description: "Order custom mailer bags for secure shipping. Eco-friendly bags ideal for clothing and small product items, available in various colors.",
    icon: "📮",
    image: "/assets/printed mailer box.jpeg",
    slug: "mailer-bags",
    metaTitle: "Shop Plastic and Customized Mailer Bags - Axis Packaging",
    metaDescription: "Order custom mailer bags for secure shipping. Eco-friendly bags ideal for clothing and small product items, available in various colors.",
  },
  {
    name: "Flexible Packaging Pouches",
    description: "Maintain food freshness with our resealable packaging pouches. Custom sizes, high-barrier materials, and vibrant printing options.",
    icon: "🥡",
    image: "/assets/packify-food-containers.png",
    slug: "flexible-pouches",
    metaTitle: "Buy Custom Flexible Packaging Pouches - Axis Packaging",
    metaDescription: "Maintain food freshness with our resealable packaging pouches. Custom sizes, high-barrier materials, and vibrant printing options.",
    h1: "Custom Flexible Packaging Pouches for Freshness",
  },
  {
    name: "Metal Tin Containers",
    description: "Searching for packaging that protects and stands out? Our custom metal tin containers offer durability and premium shelf appeal.",
    icon: "🥫",
    image: "/assets/assorted-food-containers.png",
    slug: "tin-containers",
    metaTitle: "Buy Metal Tin Containers - Custom Packaging - Axis Packaging",
    metaDescription: "Searching for packaging that protects and stands out? Our custom metal tin containers offer durability and premium shelf appeal.",
    h1: "Premium Metal Tin Containers for Standout Branding",
  },
  {
    name: "Retail POP Displays",
    description: "Showcase products beautifully with custom retail POP displays. Enhance visibility on counters and floor areas with brand-focused designs.",
    icon: "🏪",
    image: "/assets/Retail POP Displays.jpg",
    slug: "pop-displays",
    metaTitle: "Buy Retail POP Displays - Custom Solutions - Axis Packaging",
    metaDescription: "Showcase products beautifully with custom retail POP displays. Enhance visibility on counters and floor areas with brand-focused designs.",
    h1: "Custom Retail POP Displays for Enhanced Visibility",
  },
  {
    name: "Vinyl Stickers Labels",
    description: "Elevate your products with high-quality vinyl stickers and labels. Available in custom shapes, sizes, and finishes for branding and packaging.",
    icon: "🏷️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "stickers-labels",
    metaTitle: "Buy Vinyl Stickers & Labels - Custom Printing - Axis Packaging",
    metaDescription: "Add custom flair to your products with high-quality vinyl stickers and labels. Durable, waterproof, and perfect for branding impact.",
    h1: "Custom Vinyl Stickers & Labels for Brand Impact",
  },
  {
    name: "Printed Kraft Boxes",
    description: "Showcase products stylishly with sustainable kraft packaging. Custom printed boxes that combine eco-friendly materials with premium design.",
    icon: "🌱",
    image: "/assets/Printed Kraft Boxes.jpg",
    slug: "kraft-boxes",
    metaTitle: "Buy Printed Kraft Boxes - Sustainable Packaging - Axis Packaging",
    metaDescription: "Showcase products stylishly with sustainable kraft packaging. Custom printed boxes that combine eco-friendly materials with premium design.",
    h1: "Sustainable Printed Kraft Boxes for Stylish Packaging",
  },
  {
    name: "Paper Shopping Bags",
    description: "Stylish and eco-friendly paper shopping bags for retail and gifting. Custom printed with your logo for a premium brand experience.",
    icon: "🛍️",
    image: "/assets/retail-packaging-display.png",
    slug: "paper-bags",
    metaTitle: "Buy Paper Shopping Bags - Eco-Friendly - Axis Packaging",
    metaDescription: "Stylish and eco-friendly paper shopping bags for retail and gifting. Custom printed with your logo for a premium brand experience.",
    h1: "Eco-Friendly Paper Shopping Bags for Retail",
  },
  {
    name: "Eco-friendly Packaging",
    description: "Explore our range of sustainable packaging alternatives. Eco-friendly materials that protect your products and the planet.",
    icon: "♻️",
    image: "/assets/packify-eco-friendly-packaging.png",
    slug: "eco-friendly",
    metaTitle: "Buy Eco-friendly Packaging - Sustainable Solutions - Axis Packaging",
    metaDescription: "Explore our range of sustainable packaging alternatives. Eco-friendly materials that protect your products and the planet.",
    h1: "Sustainable & Eco-friendly Packaging Solutions",
  },
  {
    name: "Corrugated Shipping Boxes",
    description: "Heavy-duty corrugated boxes for safe shipping and storage. Buy custom sizes and strengths to protect your goods during transit.",
    icon: "📦",
    image: "/assets/Corrugated Shipping Boxes.jpg",
    slug: "corrugated-shipping",
    metaTitle: "Buy Corrugated Shipping Boxes - Heavy Duty - Axis Packaging",
    metaDescription: "Heavy-duty corrugated boxes for safe shipping and storage. Buy custom sizes and strengths to protect your goods during transit.",
    h1: "Heavy-Duty Corrugated Shipping Boxes for Safe Transit",
  },
  {
    name: "Custom Cosmetic Boxes",
    description: "Elegant packaging solutions for beauty and cosmetic products. Custom printed cosmetic boxes with luxury finishes and premium feel.",
    icon: "💄",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "cosmetic-boxes",
    metaTitle: "Buy Custom Cosmetic Boxes - Elegant Solutions - Axis Packaging",
    metaDescription: "Elegant packaging solutions for beauty and cosmetic products. Custom printed cosmetic boxes with luxury finishes and premium feel.",
    h1: "Elegant Custom Cosmetic Boxes for Beauty Brands",
  },
  {
    name: "Food Grade Containers",
    description: "FDA approved containers for food and beverage products. Safe, hygienic, and custom-designed packaging for all types of food.",
    icon: "🍽️",
    image: "/assets/assorted-food-containers.png",
    slug: "food-containers",
    metaTitle: "Buy Food Grade Containers - FDA Approved - Axis Packaging",
    metaDescription: "FDA approved containers for food and beverage products. Safe, hygienic, and custom-designed packaging for all types of food.",
    h1: "FDA Approved Food Grade Containers for Safety",
  },
  {
    name: "Pharmaceutical Packaging",
    description: "Compliant packaging for pharmaceutical and medical products. Secure, informative, and meeting all industry standards for safety.",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "pharmaceutical",
    metaTitle: "Buy Pharmaceutical Packaging - Compliant - Axis Packaging",
    metaDescription: "Compliant packaging for pharmaceutical and medical products. Secure, informative, and meeting all industry standards for safety.",
    h1: "Compliant Pharmaceutical & Medical Packaging",
  },
  {
    name: "Electronics Packaging",
    description: "Anti-static and protective packaging for electronic devices. Custom solutions to ensure safety from electrostatic discharge and impact.",
    icon: "📱",
    image: "/assets/packify-electronics-packaging.png",
    slug: "electronics",
    metaTitle: "Buy Electronics Packaging - Anti-Static & Protective - Axis Packaging",
    metaDescription: "Anti-static and protective packaging for electronic devices. Custom solutions to ensure safety from electrostatic discharge and impact.",
    h1: "Protective Electronics Packaging with Anti-Static Features",
  },
  {
    name: "Jewelry Gift Boxes",
    description: "Luxury presentation boxes for jewelry and precious items. Custom-designed with premium materials for an unforgettable unboxing experience.",
    icon: "💍",
    image: "/assets/luxury-cosmetic-boxes.png",
    slug: "jewelry-boxes",
    metaTitle: "Buy Jewelry Gift Boxes - Luxury Presentation - Axis Packaging",
    metaDescription: "Luxury presentation boxes for jewelry and precious items. Custom-designed with premium materials for an unforgettable unboxing experience.",
    h1: "Luxury Jewelry Gift Boxes for Premium Presentation",
  },
  {
    name: "Wine & Liquor Boxes",
    description: "Order premium custom wine and liquor boxes. Elegant designs and durable materials perfect for gifting and luxury branding.",
    icon: "🍷",
    image: "/assets/packify-hero-box4.png",
    slug: "wine-boxes",
    metaTitle: "Buy Wine & Liquor Boxes - Premium Packaging - Axis Packaging",
    metaDescription: "Premium packaging for alcoholic beverages and wine bottles. Durable, stylish, and custom-designed for safe transport and gift appeal.",
    h1: "Premium Wine & Liquor Boxes for Safe Transport",
  },
  {
    name: "Bakery & Cake Boxes",
    description: "Keep treats fresh with custom bakery and cake boxes. Durable, food-safe packaging perfect for cakes, pastries, and desserts.",
    icon: "🎂",
    image: "/assets/packify-food-packaging.png",
    slug: "bakery-boxes",
    metaTitle: "Buy Bakery & Cake Boxes - Food Safe - Axis Packaging",
    metaDescription: "Food-safe boxes perfect for cakes, pastries, and baked goods. Custom printed and available in various sizes for all your bakery needs.",
    h1: "Food-Safe Bakery & Cake Boxes for Fresh Delivery",
  },
  {
    name: "Apparel Packaging",
    description: "Elevate brand with custom apparel packaging. Premium boxes and bags designed for clothing, shoes, and fashion accessories.",
    icon: "👕",
    image: "/assets/packify-fashion-packaging.png",
    slug: "apparel-packaging",
    metaTitle: "Buy Apparel Packaging - Stylish & Durable - Axis Packaging",
    metaDescription: "Stylish boxes and bags for clothing and fashion items. Enhance your apparel brand with custom printed, high-quality packaging.",
    h1: "Stylish Apparel Packaging for Fashion Brands",
  },
  {
    name: "Subscription Boxes",
    description: "Design unique subscription boxes that excite customers. Durable, branded packaging perfect for monthly deliveries and kits.",
    icon: "📮",
    image: "/assets/custom-packaging-boxes.png",
    slug: "subscription-boxes",
    metaTitle: "Buy Subscription Boxes - Custom Branded - Axis Packaging",
    metaDescription: "Custom branded boxes for subscription and e-commerce businesses. Create a unique unboxing experience with our durable shipping boxes.",
    h1: "Custom Branded Subscription Boxes for E-Commerce",
  },
  {
    name: "Gift Wrapping Boxes",
    description: "Make every gift special with custom gift wrapping boxes. Beautiful designs and premium finishes for any occasion or brand.",
    icon: "🎁",
    image: "/assets/custom-blue-box.png",
    slug: "gift-boxes",
    metaTitle: "Buy Gift Wrapping Boxes - Beautiful Presentation - Axis Packaging",
    metaDescription: "Beautiful presentation boxes for gifts and special occasions. Custom sizes and finishes to make every gift feel extra special.",
    h1: "Beautiful Gift Wrapping Boxes for All Occasions",
  },
  {
    name: "Toy Packaging",
    description: "Shop premium toy packaging for kids, gifts, and collectibles. Custom, durable, and eco-friendly boxes perfect for storage.",
    icon: "🧸",
    image: "/assets/packify-hero-box3.png",
    slug: "toy-packaging",
    metaTitle: "Buy Toy Packaging Boxes & Custom Designs - Axis Packaging",
    metaDescription: "Shop premium toy packaging for kids, girls, and collectibles. Custom, durable, and eco-friendly boxes perfect for retail.",
    h1: "Premium Toy Packaging Boxes",
  },
  {
    name: "Book & Media Packaging",
    description: "Protect and present CDs, DVDs, and books with our media packaging. Custom designs, sturdy materials, perfect for retail and shipping.",
    icon: "📚",
    image: "/assets/Book & Media Packaging.jpg",
    slug: "media-packaging",
    metaTitle: "Buy Media & Book Packaging Solutions - Axis Packaging",
    metaDescription: "Protect and present CDs, DVDs, and books with our premium packaging. Custom designs, sturdy materials, perfect for retail and shipping.",
    h1: "Premium Media & Book Packaging for Retail & Shipping",
  },
  {
    name: "Automotive Parts Boxes",
    description: "Protect auto parts with durable custom-built packaging boxes. Custom designs, foam protection, and bulk supply options.",
    icon: "🚗",
    image: "/assets/Automotive Parts Boxes.jpg",
    slug: "automotive-boxes",
    metaTitle: "Buy Automotive Packaging Boxes for Parts - Axis Packaging",
    metaDescription: "Premium auto parts with durable custom automotive packaging boxes. Custom designs, foam protection, and bulk supply options.",
    h1: "Custom Auto Packaging Boxes for Secure Part Protection",
  },
  {
    name: "Sports Equipment Boxes",
    description: "Design your unique custom sports packaging to reflect your brand image, protect equipment, and boost product appeal with durable boxes.",
    icon: "⚽",
    image: "/assets/spports.jpg",
    slug: "sports-boxes",
    metaTitle: "Buy Custom Sports Packaging Boxes - Axis Packaging",
    metaDescription: "Design your unique custom sports packaging to reflect your brand image, protect equipment, and boost product appeal.",
    h1: "Custom Sports Packaging Boxes for Gear & Brand Impact",
  },
  {
    name: "Pet Product Packaging",
    description: "Shop premium pet product high quality custom built packaging boxes with premium finishes and sustainable options to present products.",
    icon: "🐾",
    image: "/assets/assorted-food-containers.png",
    slug: "pet-packaging",
    metaTitle: "Pet Products Packaging - Custom Solutions - Axis Packaging",
    metaDescription: "Shop premium PET, custom pet packaging boxes with premium finishes and sustainable options for pet products and toys.",
    h1: "Custom PET Packaging Boxes",
  },
  {
    name: "Hardware & Tool Boxes",
    description: "Custom hardware packaging boxes protect heavy, sharp, and high-value products from factory floor to retail shelf to customer doorstep. We manufacture custom tool boxes and hardware packaging for hand tools, power tools, drill bits, fasteners, screws, bolts, and complete tool kits — in heavy-duty corrugated and rigid stock, with retail-ready printing, branded logo placement, and structural formats engineered for weight, sharpness, and durability.",
    icon: "🔧",
    image: "/assets/Hardware & Tools Boxes.png",
    slug: "hardware-boxes",
    metaTitle: "Custom Hardware & Tool Packaging Boxes | Axis Packaging",
    metaDescription: "Custom hardware and tool boxes for drills, screws, hand tools & power tools. Heavy-duty corrugated, logo printing & wholesale rates. Free proof included.",
    h1: "Custom Hardware & Tool Packaging Boxes",
    alt: "Custom hardware and tool packaging boxes in heavy-duty corrugated by Axis Packaging",
    breadcrumbName: "Hardware & Tool Boxes",
    productsWePackageTitle: "Hardware & Tool Products We Package",
    productsWePackage: [
      { title: "Hand tool boxes", detail: "Hammer, screwdriver, wrench, and multi-tool retail packaging with hang tabs" },
      { title: "Power tool packaging", detail: "Heavy-duty corrugated with foam inserts, full-color product printing" },
      { title: "Drill bit & accessory boxes", detail: "Tray inserts, window display, blister-alternative formats" },
      { title: "Fastener & hardware packaging", detail: "Small-part tuck boxes, hang-display formats, bulk inner cartons" },
      { title: "Complete tool kit boxes", detail: "Large corrugated, foam-molded inserts, retail and e-commerce formats" },
      { title: "Industrial & auto parts packaging", detail: "Heavy-duty corrugated shippers, moisture-resistant options" },
    ],
    materials: [
      { name: "Corrugated (B/C/BC-flute)", bestFor: "Power tools, heavy tool kits, industrial shipping" },
      { name: "Double-Wall Corrugated", bestFor: "Extra-heavy or sharp hardware requiring crush resistance" },
      { name: "SBS Cardstock (16pt–24pt)", bestFor: "Hand tool retail boxes, drill bit display, fastener packaging" },
      { name: "Rigid Bux Board", bestFor: "Premium tool gift sets, professional-grade tool presentation" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Single-color"],
      finish: ["Matte", "Gloss", "Spot UV", "Kraft natural"],
      addons: ["Foam inserts", "Hang tabs", "Blister-style windows", "Tray inserts", "Moisture-resistant lining", "Custom die-cut slots for tool shapes"],
    },
    whyChoose: [
      "Heavy-duty corrugated construction — rated for tools, hardware, and dense products",
      "Custom foam and die-cut tray inserts to hold tool shapes securely",
      "Retail-ready formats: hang tabs, peg-display, shelf-stand for hardware store placement",
      "Bold CMYK printing for product specifications, safety warnings, and brand identity",
      "Moisture-resistant options for outdoor and industrial hardware packaging",
      "Free digital proof + 3D mockup with every order",
      "Low MOQ — small hardware brands to large wholesale distributors",
    ],
    faqs: [
      {
        question: "What hardware and tool products can you make packaging for?",
        answer: "Hand tools, power tools, drill bits, screwdrivers, wrenches, fasteners, screws, bolts, complete tool kits, and industrial and auto parts.",
      },
      {
        question: "What materials work best for heavy tool packaging?",
        answer: "Double-wall or BC-flute corrugated is the standard for heavy power tools and tool kits. B-flute and C-flute work well for mid-weight hand tools. For retail display of smaller hardware items, 16pt–24pt SBS cardstock provides a sharp print surface with adequate rigidity.",
      },
      {
        question: "Can you add foam inserts to tool packaging?",
        answer: "Yes. Custom die-cut foam inserts in EVA and polyurethane are available for tool boxes — holding each tool in a shaped cavity, preventing movement, and creating a premium presentation when the box is opened.",
      },
      {
        question: "Do you offer hang tab hardware packaging for retail display?",
        answer: "Yes. Hang tab formats for peg-display in hardware stores and home improvement retail are standard on our tuck-end and cardstock hardware packaging styles.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
    ],
  },
  {
    name: "Candle & Fragrance Boxes",
    description: "Custom candle boxes communicate the luxury, scent, and personality of your brand before the candle is ever lit. We manufacture candle packaging boxes and fragrance packaging for jar candles, pillar candles, taper candles, reed diffusers, wax melts, and gift sets — in premium rigid board, kraft, and cardstock, with foil stamping, soft-touch coating, and elegant finishes that match the quality of what is inside.",
    icon: "🕯️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "candle-boxes",
    metaTitle: "Custom Candle & Fragrance Boxes Packaging | Axis",
    metaDescription: "Custom candle boxes and fragrance packaging with luxury finishes, foil stamping & eco-friendly kraft. Wholesale pricing, low MOQ, free proof. Order today.",
    h1: "Custom Candle & Fragrance Packaging Boxes",
    alt: "Custom luxury candle boxes with gold foil stamp and soft-touch finish by Axis Packaging",
    breadcrumbName: "Candle & Fragrance Boxes",
    productsWePackageTitle: "Candle & Fragrance Products We Package",
    productsWePackage: [
      { title: "Jar candle boxes", detail: "Tuck-end, window display, sleeve formats; foam inserts for protection" },
      { title: "Pillar & taper candle boxes", detail: "Tall-format rigid and cardstock, custom inserts" },
      { title: "Reed diffuser packaging", detail: "Rigid magnetic lid, foam-molded inserts, luxury presentation" },
      { title: "Wax melt & tealight boxes", detail: "Window display, multi-cavity tray inserts, retail formats" },
      { title: "Candle gift sets", detail: "Two-piece rigid boxes, ribbon closures, tissue lining, branded tissue" },
      { title: "Fragrance & perfume cartons", detail: "Precision-fit cardstock cartons, foil-stamped, premium finish" },
    ],
    materials: [
      { name: "Rigid Bux Board", bestFor: "Luxury candle gift boxes, reed diffusers, premium brands" },
      { name: "SBS Cardstock (14pt–24pt)", bestFor: "Retail jar candle boxes, fragrance cartons, high-print quality" },
      { name: "Kraft Board", bestFor: "Eco candle brands, artisan and natural wax candle packaging" },
      { name: "Corrugated (E-flute)", bestFor: "Candle e-commerce shipping, multi-candle order fulfillment" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Interior printing available"],
      finish: ["Matte", "Gloss", "Soft-touch", "Gold/Silver foil stamp", "Spot UV", "Emboss", "Deboss", "Holographic foil"],
      addons: ["Magnetic closures", "Ribbon pulls", "Window cutouts", "Foam inserts", "Tissue lining", "Fragrance info tags"],
    },
    whyChoose: [
      "Luxury finishing — foil stamp, emboss, soft-touch — standard for candle brands",
      "Rigid gift box formats with magnetic closures for premium candle lines",
      "Fragrance info tag printing and interior-printed lid options",
      "Foam and card inserts to protect glass jars during shipping and retail display",
      "Eco-friendly kraft options for natural wax and sustainable candle brands",
      "Free digital proof + 3D mockup with every order",
      "Low MOQ — indie candle makers to large wholesale brands",
    ],
    faqs: [
      {
        question: "What candle types can you make packaging for?",
        answer: "Jar candles, pillar candles, taper candles, votive candles, tealights, wax melts, reed diffusers, and candle gift sets.",
      },
      {
        question: "Can you make luxury gift boxes for candles?",
        answer: "Yes. Our luxury candle gift boxes in rigid board with magnetic closures, ribbon pulls, foil-stamped logos, and tissue lining are built for premium candle brands and gifting occasions.",
      },
      {
        question: "What finishes work best for candle packaging?",
        answer: "Soft-touch coating with gold foil stamping is the most popular combination for premium candle brands. Matte lamination with Spot UV is the modern minimalist option. Gloss lamination suits bold, colorful retail candle packaging.",
      },
      {
        question: "Do you offer eco-friendly candle boxes?",
        answer: "Yes. Recycled kraft, FSC-certified cardstock, and biodegradable materials with water-based inks are all available — ideal for natural wax, soy, and coconut candle brands.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
    ],
  },
  {
    name: "Supplement Packaging",
    description: "Custom supplement packaging is one of the most regulated and brand-sensitive categories in retail. Consumers judge supplement brands by packaging before they read the label. We manufacture custom supplement boxes for protein powders, vitamins, capsules, softgels, wellness shots, and health drinks — in materials compliant with FDA labeling standards, with full-color printing, tamper-evident options, and premium finishes that communicate quality and trust.",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "supplement-bottles",
    metaTitle: "Custom Supplement Packaging Boxes & Bottles | Axis",
    metaDescription: "Custom supplement packaging boxes for protein, vitamins, capsules & wellness bottles. FDA-compliant materials, logo printing & wholesale rates. Free proof included.",
    h1: "Custom Supplement Packaging Boxes",
    alt: "Custom supplement packaging boxes with nutritional label printing by Axis Packaging",
    breadcrumbName: "Supplement Packaging",
    productsWePackageTitle: "Supplement Products We Package",
    productsWePackage: [
      { title: "Protein powder boxes", detail: "Heavy-duty corrugated, moisture-resistant, large-format branding" },
      { title: "Vitamin & capsule boxes", detail: "Tuck-end retail, auto-bottom, child-resistant options available" },
      { title: "Softgel & tablet packaging", detail: "Sealed tuck boxes, sleeve-and-tray formats, foil-lined options" },
      { title: "Wellness shot & drink boxes", detail: "Bottle carriers, six-pack partitions, branded retail cartons" },
      { title: "Pre-workout & sports nutrition boxes", detail: "Bold CMYK printing, metallic finish, high-impact shelf presence" },
      { title: "Supplement gift sets & starter kits", detail: "Rigid gift boxes, branded insert trays, premium unboxing" },
    ],
    materials: [
      { name: "SBS Cardstock (16pt–24pt)", bestFor: "Retail vitamin and capsule boxes, high-resolution label printing" },
      { name: "Corrugated (B/C-flute)", bestFor: "Protein powder shipping, bulk supplement fulfillment" },
      { name: "Rigid Bux Board", bestFor: "Premium wellness brands, supplement gift sets" },
      { name: "Moisture-Resistant Lining", bestFor: "Powder and liquid supplement packaging" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Nutritional label printing"],
      finish: ["Matte", "Gloss", "Soft-touch", "Metallic foil", "Spot UV", "Emboss/Deboss"],
      addons: ["Tamper-evident seals", "Child-resistant closures", "Foil lining", "QR code printing", "Window cutouts"],
    },
    whyChoose: [
      "FDA-compliant materials available for supplement retail packaging",
      "Nutritional label panel printing with accurate CMYK color reproduction",
      "Moisture-resistant options for powder and liquid supplement products",
      "Bold shelf-presence designs — metallic foil, Spot UV, high-impact CMYK",
      "Child-resistant and tamper-evident options available",
      "Free digital proof + 3D mockup with every order",
      "Low MOQ — startup supplement brands to large wholesale runs",
    ],
    faqs: [
      {
        question: "What types of supplements can you make packaging for?",
        answer: "Protein powders, vitamins, capsules, softgels, tablets, wellness shots, pre-workout, sports nutrition blends, and supplement gift sets.",
      },
      {
        question: "Are your supplement packaging materials FDA-compliant?",
        answer: "Yes. We use food-safe, FDA-compliant materials suitable for supplement retail packaging. All materials and inks comply with applicable health and safety standards.",
      },
      {
        question: "Can you print nutritional labels and supplement facts panels?",
        answer: "Yes. Full nutritional label printing with accurate CMYK color matching is available on all supplement box formats. We support supplement facts panel placement and regulatory text layout.",
      },
      {
        question: "Do you offer tamper-evident or child-resistant options?",
        answer: "Yes. Tamper-evident seals and child-resistant closure options are available for capsule and tablet supplement packaging.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
    ],
  },
  {
    name: "Craft & Hobby Boxes",
    description: "Custom craft boxes and hobby packaging turn everyday creative supplies into a branded experience. We manufacture packaging for DIY kit brands, craft subscription boxes, yarn and fabric suppliers, scrapbooking products, jewelry-making sets, and art and hobby retailers — in kraft, cardstock, and corrugated, with full-color printing and eco-friendly options.",
    icon: "🎨",
    image: "/assets/Craft & Hobby Boxes.jpg",
    slug: "craft-boxes",
    metaTitle: "Custom Craft & Hobby Boxes Packaging | Axis Packaging",
    metaDescription: "Custom craft and hobby boxes for DIY kits, yarn, scrapbooking, jewelry making & more. Eco-friendly kraft, logo printing & wholesale pricing. Free proof included.",
    h1: "Custom Craft & Hobby Boxes",
    alt: "Custom craft and hobby boxes in eco-friendly kraft by Axis Packaging",
    breadcrumbName: "Craft & Hobby Boxes",
    productsWePackageTitle: "Craft & Hobby Products We Package",
    productsWePackage: [
      { title: "DIY kit boxes", detail: "Subscription mailers, multi-item dividers, branded tissue and inserts" },
      { title: "Yarn & fabric packaging", detail: "Sleeve wraps, band wraps, hang-tag formats, kraft natural finish" },
      { title: "Scrapbooking & paper craft boxes", detail: "Flat-pack rigid, tuck-end retail, window display" },
      { title: "Jewelry making kits", detail: "Tray-insert boxes, foam slots, gift-ready rigid formats" },
      { title: "Paint-by-numbers & canvas kits", detail: "Corrugated mailers, foam padding, branded exterior" },
      { title: "General hobby supply boxes", detail: "Retail shelf, hang tab, window cutout formats" },
    ],
    materials: [
      { name: "Kraft Board", bestFor: "Eco craft brands, artisan hobby suppliers, subscription boxes" },
      { name: "SBS Cardstock (14pt–24pt)", bestFor: "Retail hobby shelf packaging, vivid CMYK printing" },
      { name: "Corrugated (E/B-flute)", bestFor: "DIY kit shipping, subscription mailers, heavier hobby sets" },
      { name: "Rigid Bux Board", bestFor: "Premium hobby gift boxes, luxury craft sets" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Single-color"],
      finish: ["Matte", "Gloss", "Soft-touch", "Kraft natural", "Foil stamp", "Spot UV"],
      addons: ["Die-cut windows", "Hang tabs", "Custom dividers", "Foam inserts", "Tissue lining"],
    },
    whyChoose: [
      "Eco-friendly kraft options — standard for craft and hobby brands",
      "Custom dividers and inserts for multi-item DIY kit organization",
      "Subscription box formats with branded interior and exterior printing",
      "Retail-ready hang tabs and window cutouts available",
      "Low MOQ — indie makers to large wholesale all accommodated",
      "Free digital proof + 3D mockup with every order",
    ],
    faqs: [
      {
        question: "What craft and hobby products can you package?",
        answer: "DIY kits, yarn, fabric, scrapbooking supplies, jewelry-making sets, paint-by-numbers kits, canvas sets, and general hobby supply bundles.",
      },
      {
        question: "Can you make branded subscription boxes for craft brands?",
        answer: "Yes. We produce custom craft subscription boxes in corrugated mailer formats with full exterior and interior printing, custom dividers, and tissue paper for organized unboxing.",
      },
      {
        question: "Do you offer eco-friendly craft packaging?",
        answer: "Yes. Recycled kraft, FSC-certified corrugated, and biodegradable materials with water-based inks are all available — preferred by most craft and hobby brands.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
      {
        question: "How long does production take?",
        answer: "7–10 business days after proof approval. Rush turnaround available.",
      },
    ],
  },
  {
    name: "Garden & Plant Packaging",
    description: "Custom garden packaging and plant packaging boxes keep plants alive, seeds protected, and garden brands visible. We manufacture packaging for nurseries, plant subscription services, seed companies, and garden supply brands — in eco-friendly materials with full-color printing, ventilation options, and moisture-resistant construction built for live and dry garden products.",
    icon: "🌱",
    image: "/assets/packify-eco-friendly-packaging.png",
    slug: "custom-garden-plant-packaging",
    metaTitle: "Custom Garden & Plant Packaging Boxes | Axis Packaging",
    metaDescription: "Custom gardening and plant packaging boxes for seeds, live plants, pots & tools. Eco-friendly materials, logo printing & wholesale pricing. Free proof included.",
    h1: "Custom Garden & Plant Packaging Boxes",
    alt: "Custom garden and plant packaging boxes in eco-friendly kraft by Axis Packaging",
    breadcrumbName: "Garden & Plant Packaging",
    productsWePackageTitle: "Garden Products We Package",
    productsWePackage: [
      { title: "Seed boxes", detail: "Tuck-end or window display, moisture-resistant, printed with planting info" },
      { title: "Live plant shipping boxes", detail: "Ventilated corrugated, pot inserts, handles, size-to-roots construction" },
      { title: "Potted plant packaging", detail: "Corrugated with cardboard or foam pot-holders to prevent tipping in transit" },
      { title: "Soil & fertilizer boxes", detail: "Heavy-duty corrugated, moisture barrier lining, branded print" },
      { title: "Garden tool packaging", detail: "Retail display boxes, hang tab formats, full-color product printing" },
      { title: "Garden gift sets & subscription boxes", detail: "Branded mailers with dividers, tissue, and eco-friendly materials" },
    ],
    materials: [
      { name: "Corrugated (E/B/C-flute)", bestFor: "Live plant shipping, heavy-duty garden tools, soil boxes" },
      { name: "Kraft Board", bestFor: "Seed boxes, eco garden brands, subscription mailers" },
      { name: "SBS Cardstock (14pt–24pt)", bestFor: "Retail seed display, garden gift sets, tool packaging" },
      { name: "Moisture-Resistant Lining", bestFor: "Soil, fertilizer, and live plant boxes needing humidity control" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Single-color"],
      finish: ["Matte", "Gloss", "Soft-touch", "Spot UV", "Kraft natural"],
      addons: ["Ventilation holes", "Pot inserts & trays", "Hang tabs", "Die-cut windows", "Carry handles", "Moisture barrier lining"],
    },
    whyChoose: [
      "Eco-friendly materials: FSC-certified, recycled kraft, biodegradable options",
      "Ventilated construction available for live plant shipping boxes",
      "Custom pot-holder inserts to prevent tipping and root damage in transit",
      "Moisture-resistant lining options for soil, fertilizer, and wet products",
      "Full-color CMYK printing for planting instructions, brand logos, and product info",
      "Free digital proof + 3D mockup with every order",
      "Low MOQ — nurseries, startups, and large wholesale all accommodated",
    ],
    faqs: [
      {
        question: "What types of garden products can you make packaging for?",
        answer: "Seeds, live plants, potted plants, soil, fertilizer, garden tools, grow kits, plant subscription boxes, and garden gift sets.",
      },
      {
        question: "Can you make boxes for shipping live plants?",
        answer: "Yes. Our live plant shipping boxes use ventilated corrugated construction with custom pot-holder inserts to keep plants stable, roots protected, and plants breathing throughout transit.",
      },
      {
        question: "Are your garden packaging materials eco-friendly?",
        answer: "Yes. All our eco-friendly garden packaging options include recycled kraft, FSC-certified corrugated, and biodegradable cardstock — ideal for garden and plant brands whose customers expect sustainable packaging.",
      },
      {
        question: "Can seed boxes include moisture protection?",
        answer: "Yes. We offer moisture-resistant lining and sealed construction for seed packaging to protect seeds from humidity and moisture damage during storage and shipping.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
    ],
  },
  {
    name: "Office Supply Boxes",
    description: "Shop office supply boxes for storage and organization, available in small, large, paper or fabric-covered designs for any workspace.",
    icon: "📎",
    image: "/assets/packify-retail-boxes.png",
    slug: "office-boxes",
    metaTitle: "Shop Office Supply Boxes - Custom & Premium - Axis Packaging",
    metaDescription: "Shop office supply boxes for storage and organization, available in small, large, paper or cardboard designs for brands.",
    h1: "Office Supply Boxes — Storage and Organization Solutions",
  },
  {
    name: "Home Decor Packaging",
    description: "Shop home decor packaging including decorative boxes, storage solutions, and subscription boxes. Perfect for gifts, home organization, and retail.",
    icon: "🏠",
    image: "/assets/packify-custom-boxes.png",
    slug: "home-decor",
    metaTitle: "Buy Home Decor Packaging - Premium Creation - Axis Packaging",
    metaDescription: "Shop home decor packaging including decorative boxes, storage solutions, and subscription boxes. Perfect for gifts and collectibles.",
    h1: "Home Decor Packaging — Decoration & Storage Boxes",
  },
  {
    name: "Musical Instrument Cases",
    description: "Protect instruments with custom musical instrument cases. Durable, padded packaging designed for safe transport and professional presentation.",
    icon: "🎵",
    image: "/assets/Musical Instrument Cases.jpg",
    slug: "music-cases",
    metaTitle: "Buy Musical Instrument Cases - Protective - Axis Packaging",
    metaDescription: "Protective cases and packaging for musical instruments. Ensure safe transport and storage with our durable, custom-fit solutions.",
    h1: "Protective Musical Instrument Cases and Packaging",
  },
  {
    name: "Custom Art Boxes",
    description: "Protect and present your art supplies with packaging built for the creative industry. We manufacture custom art boxes for paint brushes, colored pencils, crayons, watercolor sets, sketchbooks, and complete art kits — in any size, material, and finish, with full-color printing and low minimum orders.",
    icon: "🖼️",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "custom-art-boxes",
    metaTitle: "Custom Art Boxes & Art Supply Packaging | Axis Packaging",
    metaDescription: "Custom art boxes for paint brushes, pencils, crayons, watercolors & art kits. Logo printing, die-cut windows, wholesale pricing. Free proof included.",
    h1: "Custom Art Boxes",
    alt: "Custom art supply packaging boxes with die-cut window and CMYK printing by Axis Packaging",
    breadcrumbName: "Art Boxes",
    productsWePackageTitle: "Art Supply Products We Package",
    productsWePackage: [
      { title: "Paint brush boxes", detail: "Slim tuck-end or display formats, foam inserts, die-cut windows" },
      { title: "Colored pencil & crayon boxes", detail: "Slot trays, window cutouts, vibrant CMYK printing" },
      { title: "Watercolor & paint set boxes", detail: "Rigid or tuck-end, foam-lined, gift-ready" },
      { title: "Art kit & craft set boxes", detail: "Multi-item dividers, branded tissue, mailer formats" },
      { title: "Sketchbook & art paper packaging", detail: "Sleeve wraps, corrugated mailers, band wraps" },
    ],
    materials: [
      { name: "SBS Cardstock (14pt–24pt)", bestFor: "Retail shelf packaging, vivid color printing" },
      { name: "Kraft Board", bestFor: "Eco-friendly and artisan art brands" },
      { name: "Corrugated (E/B-flute)", bestFor: "Shipping, e-commerce, subscription boxes" },
      { name: "Rigid Bux Board", bestFor: "Premium artist gift sets, luxury unboxing" },
    ],
    printingFinishing: {
      print: ["Full-color CMYK", "PMS Pantone", "Single-color"],
      finish: ["Gloss", "Matte", "Soft-touch", "Gold/Silver Foil", "Spot UV", "Emboss", "Deboss"],
      addons: ["Die-cut windows", "Hang tabs", "Acetate film", "Foam inserts", "Cardboard slot trays"],
    },
    whyChoose: [
      "Color-accurate CMYK printing — critical for art brands",
      "Custom foam and slot inserts for every product type",
      "Retail-ready formats: hang tabs, peg-display, shelf-stand",
      "Eco-friendly materials: FSC-certified, recycled kraft, water-based inks",
      "Free digital proof + 3D mockup with every order",
      "Low MOQ — small batch to large wholesale runs",
    ],
    faqs: [
      {
        question: "What art supplies can you make boxes for?",
        answer: "Paint brushes, colored pencils, crayons, markers, watercolors, acrylic paint sets, sketchbooks, art kits, and gift sets.",
      },
      {
        question: "Can I add a die-cut window to my art boxes?",
        answer: "Yes. Die-cut windows with acetate film are available on all tuck-end and retail box styles — ideal for pencil, crayon, and brush packaging so buyers can see the product before purchasing.",
      },
      {
        question: "Do you offer eco-friendly art packaging?",
        answer: "Yes. Recycled kraft, FSC-certified corrugated, and biodegradable cardstock are all available with water-based inks.",
      },
      {
        question: "What is the minimum order quantity?",
        answer: "MOQ varies by box style. Contact us with your product type and quantity for a quote.",
      },
      {
        question: "How long does production take?",
        answer: "7–10 business days after proof approval. Rush turnaround available.",
      },
    ],
  },
];

export const PRODUCT_CATEGORIES = _PRODUCT_CATEGORIES.map((product) =>
  PRODUCT_ENRICHMENTS[product.slug]
    ? { ...product, ...PRODUCT_ENRICHMENTS[product.slug] }
    : product
);

export const TRUST_INDICATORS = [
  { text: "10+ Years Experience", icon: "⭐" },
  { text: "ISO 9001 Certified", icon: "🏆" },
  { text: "24/7 Customer Support", icon: "📞" },
  { text: "Free Design Consultation", icon: "🎨" },
];

export const INDUSTRIES = [
  {
    name: "Apparel",
    description: "Pair your apparel with one-of-a-kind custom printed clothing boxes. Enhance brand appeal with premium fashion packaging.",
    icon: "👕",
    image: "/assets/packify-fashion-packaging.png",
    slug: "apparel",
    metaTitle: "Buy Apparel Packaging Boxes - Custom Clothing Solutions",
    metaDescription: "Pair your apparel with one-of-a-kind custom printed clothing boxes. Enhance brand appeal with premium fashion packaging.",
    h1: "Custom Apparel Packaging Boxes for Fashion Brands",
  },
  {
    name: "Bakery & Cake",
    description: "Show off your baked goods with personalized cake and bakery boxes. Food-safe, durable, and custom-designed for freshness.",
    icon: "🍰",
    image: "/assets/packify-food-packaging.png",
    slug: "bakery-cake",
    metaTitle: "Buy Bakery & Cake Packaging - Custom Boxes - Axis Packaging",
    metaDescription: "Show off your baked goods with personalized cake and bakery boxes. Food-safe, durable, and custom-designed for freshness.",
    h1: "Custom Bakery & Cake Packaging Solutions",
  },
  {
    name: "Beer & Liquor",
    description: "Premium packaging for alcoholic beverages. Custom-designed boxes for beer and liquor that ensure safe transport and brand presence.",
    icon: "🍺",
    image: "/assets/custom-blue-box.png",
    slug: "beer-liquor",
    metaTitle: "Buy Beer & Liquor Packaging - Premium Solutions - Axis Packaging",
    metaDescription: "Premium packaging for alcoholic beverages. Custom-designed boxes for beer and liquor that ensure safe transport and brand presence.",
    h1: "Premium Beer & Liquor Packaging Solutions",
  },
  {
    name: "Beverage",
    description: "Custom packaging for all types of beverages. From cans to bottles, we provide high-quality solutions that protect and present your drink brands.",
    icon: "🥤",
    image: "/assets/packify-food-containers.png",
    slug: "beverage",
    metaTitle: "Buy Beverage Packaging Solutions - Custom Designs - Axis Packaging",
    metaDescription: "Custom packaging for all types of beverages. From cans to bottles, we provide high-quality solutions that protect and present your drink brands.",
    h1: "Custom Beverage Packaging Solutions",
  },
  {
    name: "Candle",
    description: "Elegant packaging for candle products. Custom printed candle boxes with luxury finishes and protective inserts.",
    icon: "🕯️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "candle",
    metaTitle: "Buy Custom Candle Packaging - Elegant Boxes - Axis Packaging",
    metaDescription: "Elegant packaging for candle products. Custom printed candle boxes with luxury finishes and protective inserts.",
    h1: "Elegant Custom Candle Packaging Solutions",
  },
  {
    name: "Candy & Sweets",
    description: "Sweet packaging solutions for confectionery. Custom candy boxes and packaging that attract customers and keep treats fresh.",
    icon: "🍬",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "candy-sweets",
    metaTitle: "Buy Candy & Sweets Packaging - Custom Designs - Axis Packaging",
    metaDescription: "Sweet packaging solutions for confectionery. Custom candy boxes and packaging that attract customers and keep treats fresh.",
    h1: "Custom Candy & Sweets Packaging Solutions",
  },
  {
    name: "Cannabis",
    description: "Custom-crafted tamper proof marijuana packaging. Compliant, secure, and brand-focused solutions for the cannabis industry.",
    icon: "🌿",
    image: "/assets/packify-cannabis-packaging.png",
    slug: "cannabis",
    metaTitle: "Buy Cannabis Packaging - Tamper Proof Solutions - Axis Packaging",
    metaDescription: "Custom-crafted tamper proof marijuana packaging. Compliant, secure, and brand-focused solutions for the cannabis industry.",
    h1: "Compliant & Secure Cannabis Packaging Solutions",
  },
  {
    name: "Chocolate",
    description: "Premium custom chocolate boxes and packaging. Elegant designs and food-safe materials to showcase your luxury chocolates.",
    icon: "🍫",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "chocolate",
    metaTitle: "Buy Custom Chocolate Boxes - Premium Packaging - Axis Packaging",
    metaDescription: "Premium custom chocolate boxes and packaging. Elegant designs and food-safe materials to showcase your luxury chocolates.",
    h1: "Premium Custom Chocolate Packaging Solutions",
  },
  {
    name: "Coffee",
    description: "Packaging solutions for coffee products. Custom bags and boxes that maintain freshness and highlight your brand's unique flavor.",
    icon: "☕",
    image: "/assets/packify-food-containers.png",
    slug: "coffee",
    metaTitle: "Buy Coffee Packaging Solutions - Custom Designs - Axis Packaging",
    metaDescription: "Packaging solutions for coffee products. Custom bags and boxes that maintain freshness and highlight your brand's unique flavor.",
    h1: "Custom Coffee Packaging Solutions for Freshness",
  },
  {
    name: "Cosmetics",
    description: "Custom printed cosmetic boxes and packaging. Luxury finishes and brand-focused designs for all your beauty products.",
    icon: "💄",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "cosmetics",
    metaTitle: "Buy Cosmetics Packaging - Custom Printed Boxes - Axis Packaging",
    metaDescription: "Custom printed cosmetic boxes and packaging. Luxury finishes and brand-focused designs for all your beauty products.",
    h1: "Custom Cosmetics Packaging Solutions for Beauty Brands",
  },
  {
    name: "E-Commerce",
    description: "Packaging solutions for online businesses. Durable shipping boxes and mailers designed for the rigors of e-commerce delivery.",
    icon: "🛒",
    image: "/assets/e-commerce.jpg",
    slug: "ecommerce",
    metaTitle: "Buy E-Commerce Packaging - Secure Solutions - Axis Packaging",
    metaDescription: "Packaging solutions for online businesses. Durable shipping boxes and mailers designed for the rigors of e-commerce delivery.",
    h1: "Durable E-Commerce Packaging Solutions for Online Retail",
  },
  {
    name: "Electronics",
    description: "Protective packaging for electronic devices. Custom-designed solutions to prevent damage and ensure safe delivery of sensitive electronics.",
    icon: "📱",
    image: "/assets/packify-electronics-packaging.png",
    slug: "electronics",
    metaTitle: "Buy Electronics Packaging - Custom Protective - Axis Packaging",
    metaDescription: "Protective packaging for electronic devices. Custom-designed solutions to prevent damage and ensure safe delivery of sensitive electronics.",
    h1: "Protective Electronics Packaging Solutions",
  },
  {
    name: "Food",
    description: "Safe and compliant food packaging solutions. FDA approved materials and custom designs to keep your food products secure and appetizing.",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "food",
    metaTitle: "Buy Food Packaging Solutions - Safe & Compliant - Axis Packaging",
    metaDescription: "Safe and compliant food packaging solutions. FDA approved materials and custom designs to keep your food products secure and appetizing.",
    h1: "Safe & Compliant Custom Food Packaging Solutions",
  },
  {
    name: "Gift",
    description: "Beautiful packaging for gift items. Custom gift boxes and wrapping solutions that make every occasion extra special.",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "gift",
    metaTitle: "Buy Gift Packaging - Beautiful & Custom - Axis Packaging",
    metaDescription: "Beautiful packaging for gift items. Custom gift boxes and wrapping solutions that make every occasion extra special.",
    h1: "Beautiful & Custom Gift Packaging Solutions",
  },
  {
    name: "Jewelry",
    description: "Luxury packaging for jewelry and accessories. Custom-designed boxes and displays that reflect the elegance of your pieces.",
    icon: "💍",
    image: "/assets/luxury-cosmetic-boxes.png",
    slug: "jewelry",
    metaTitle: "Buy Jewelry Packaging - Luxury Solutions - Axis Packaging",
    metaDescription: "Luxury packaging for jewelry and accessories. Custom-designed boxes and displays that reflect the elegance of your pieces.",
    h1: "Luxury Jewelry Packaging Solutions",
  },
  {
    name: "Pets",
    description: "Packaging for pet products and supplies. Custom-designed boxes and bags for pet food, toys, and grooming items.",
    icon: "🐾",
    image: "/assets/assorted-food-containers.png",
    slug: "pets",
    metaTitle: "Buy Pet Product Packaging - Custom Solutions - Axis Packaging",
    metaDescription: "Packaging for pet products and supplies. Custom-designed boxes and bags for pet food, toys, and grooming items.",
    h1: "Custom Pet Product Packaging Solutions",
  },
  {
    name: "Pharmaceutical",
    description: "Compliant packaging for pharmaceutical products. Safe, secure, and meeting all industry standards for medical and health supplies.",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "pharmaceutical",
    metaTitle: "Buy Pharmaceutical Packaging - Compliant - Axis Packaging",
    metaDescription: "Compliant packaging for pharmaceutical products. Safe, secure, and meeting all industry standards for medical and health supplies.",
    h1: "Compliant Pharmaceutical Packaging Solutions",
  },
  {
    name: "Presentation",
    description: "Professional presentation packaging. Custom-designed boxes and folders that showcase your brand and products with elegance.",
    icon: "📊",
    image: "/assets/packify-retail-boxes.png",
    slug: "presentation",
    metaTitle: "Buy Presentation Packaging - Professional - Axis Packaging",
    metaDescription: "Professional presentation packaging. Custom-designed boxes and folders that showcase your brand and products with elegance.",
    h1: "Professional Presentation Packaging Solutions",
  },
  {
    name: "Restaurant",
    description: "Packaging for restaurant and food service. Custom-designed takeout boxes and bags that represent your brand and keep food fresh.",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "restaurant",
    metaTitle: "Buy Restaurant Packaging - Custom Solutions - Axis Packaging",
    metaDescription: "Packaging for restaurant and food service. Custom-designed takeout boxes and bags that represent your brand and keep food fresh.",
    h1: "Custom Restaurant Packaging Solutions for Food Service",
  },
  {
    name: "Retail",
    description: "Eye-catching retail displays and packaging. Stand out on the shelf with our custom-designed retail packaging solutions.",
    icon: "🏪",
    image: "/assets/packify-retail-packaging.png",
    slug: "retail",
    metaTitle: "Buy Retail Packaging - Eye-Catching Designs - Axis Packaging",
    metaDescription: "Eye-catching retail displays and packaging. Stand out on the shelf with our custom-designed retail packaging solutions.",
    h1: "Eye-Catching Retail Packaging & Display Solutions",
  },
  {
    name: "Shipping",
    description: "Secure shipping and mailer solutions. Durable custom boxes designed for logistics and safe delivery of your products.",
    icon: "📦",
    image: "/assets/packify-shipping-boxes.png",
    slug: "shipping",
    metaTitle: "Buy Shipping Packaging - Secure Solutions - Axis Packaging",
    metaDescription: "Secure shipping and mailer solutions. Durable custom boxes designed for logistics and safe delivery of your products.",
    h1: "Secure Shipping & Mailer Packaging Solutions",
  },
  {
    name: "Soap",
    description: "Packaging for soap and personal care products. Custom printed soap boxes that highlight your brand's unique fragrance and style.",
    icon: "🧼",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "soap",
    metaTitle: "Buy Soap Packaging - Custom Designs - Axis Packaging",
    metaDescription: "Packaging for soap and personal care products. Custom printed soap boxes that highlight your brand's unique fragrance and style.",
    h1: "Custom Soap & Personal Care Packaging Solutions",
  },
  {
    name: "Toy",
    description: "Fun and safe packaging for toys. Custom-designed boxes that attract kids and meet all safety requirements for toy brands.",
    icon: "🧸",
    image: "/assets/packify-retail-boxes.png",
    slug: "toy",
    metaTitle: "Buy Toy Packaging - Safe & Fun Designs - Axis Packaging",
    metaDescription: "Fun and safe packaging for toys. Custom-designed boxes that attract kids and meet all safety requirements for toy brands.",
    h1: "Safe & Fun Custom Toy Packaging Solutions",
  },
  {
    name: "Tea",
    description: "Elegant packaging for tea products. Custom bags and boxes that preserve flavor and provide a premium experience for tea drinkers.",
    icon: "🫖",
    image: "/assets/packify-food-containers.png",
    slug: "tea",
    metaTitle: "Buy Tea Packaging - Elegant Solutions - Axis Packaging",
    metaDescription: "Elegant packaging for tea products. Custom bags and boxes that preserve flavor and provide a premium experience for tea drinkers.",
    h1: "Elegant Custom Tea Packaging Solutions",
  },
  {
    name: "Wine",
    description: "Premium packaging for wine and spirits. Custom-designed boxes and displays that reflect the luxury and quality of your brand.",
    icon: "🍷",
    image: "/assets/custom-blue-box.png",
    slug: "wine",
    metaTitle: "Buy Wine Packaging - Premium Solutions - Axis Packaging",
    metaDescription: "Premium packaging for wine and spirits. Custom-designed boxes and displays that reflect the luxury and quality of your brand.",
    h1: "Premium Wine & Spirit Packaging Solutions",
  },
];

export const CORRUGATED_STYLES = [
  {
    name: "Single Wall Corrugated",
    description: "Standard corrugated boxes with one layer of fluting",
    image: "/assets/packify-corrugated-boxes.png",
    slug: "single-wall",
  },
  {
    name: "Double Wall Corrugated",
    description: "Heavy-duty boxes with two layers of fluting for extra strength",
    image: "/assets/packify-custom-boxes.png",
    slug: "double-wall",
  },
  {
    name: "Triple Wall Corrugated",
    description: "Maximum strength boxes with three layers of fluting",
    image: "/assets/packify-shipping-boxes.png",
    slug: "triple-wall",
  },
  {
    name: "Die Cut Corrugated",
    description: "Custom shaped corrugated boxes for unique packaging needs",
    image: "/assets/packify-display-boxes.png",
    slug: "die-cut",
  },
];

export const CORRUGATED_OPTIONS = [
  {
    name: "E-Flute",
    description: "Thin, smooth surface perfect for printing",
    image: "/assets/packify-custom-boxes.png",
    slug: "e-flute",
  },
  {
    name: "B-Flute",
    description: "Good cushioning and compression resistance",
    image: "/assets/packify-corrugated-boxes.png",
    slug: "b-flute",
  },
  {
    name: "C-Flute",
    description: "Most common, excellent all-around performance",
    image: "/assets/packify-shipping-boxes.png",
    slug: "c-flute",
  },
  {
    name: "BC-Flute",
    description: "Double wall combination for maximum strength",
    image: "/assets/packify-custom-boxes.png",
    slug: "bc-flute",
  },
];

export const CORRUGATED_INSPIRATIONS = [
  {
    name: "Retail Display Boxes",
    description: "Eye-catching displays for retail environments",
    image: "/assets/packify-display-boxes.png",
    slug: "retail-displays",
  },
  {
    name: "Shipping Solutions",
    description: "Durable shipping boxes for e-commerce",
    image: "/assets/packify-shipping-boxes.png",
    slug: "shipping-solutions",
  },
  {
    name: "Product Packaging",
    description: "Custom product packaging with branding",
    image: "/assets/packify-custom-boxes.png",
    slug: "product-packaging",
  },
  {
    name: "Point of Purchase",
    description: "POP displays for in-store marketing",
    image: "/assets/packify-display-packaging.png",
    slug: "pop-displays",
  },
];

export const PACKAGING_SERVICES = [
  {
    name: "Structural Design & Engineering",
    description: "Our packaging experts design and engineer innovative structures",
    image: "/assets/packify-custom-boxes.png",
    slug: "structural-design",
  },
  {
    name: "Packaging Artwork Design",
    description: "Professional artwork design for your packaging",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "artwork-design",
  },
  {
    name: "Sample & Prototyping",
    description: "Create physical samples and 3D prototypes",
    image: "/assets/packify-custom-boxes.png",
    slug: "sampling-prototyping",
  },
  {
    name: "Quality Control",
    description: "Rigorous quality control and testing",
    image: "/assets/packify-custom-boxes.png",
    slug: "quality-control",
  },
];

export const CERTIFICATIONS = [
  "ISO 9001:2015",
  "FSC Certified",
  "FDA Approved Materials",
  "ROHS Compliant",
  "Recyclable Materials",
];
