export const COMPANY_INFO = {
  name: "Axis Packaging",
  tagline: "Your Box, Your Brand",
  phone: "+447367066309",
  email: "info@theaxispackaging.com",
  address: "104 Pudsey Road, Leeds, LS12 3TZ, United Kingdom.",
  hours: "Mon-Fri: 8AM-6PM PST",
};

export const NAVIGATION_ITEMS = [
  { name: "Home", href: "/" },
  { name: "Products", href: "/products" },
  { name: "Industries", href: "/industries" },
  { name: "Sustainability", href: "/sustainability" },
];

export const PRODUCT_CATEGORIES = [
  {
    name: "Custom Folding Carton Boxes",
    description: "Durable folding cartons crafted from thin, flexible paperboard",
    icon: "📦",
    image: "/assets/packify-custom-boxes.png",
    slug: "folding-carton-boxes",
    metaTitle: "Premium and Customized Folding Carton Boxes - Axis Packaging",
    metaDescription: "Get custom folding carton boxes with fast turnaround, fast production, and high quality perfect for retail, gifting, and more.",
    h1: "Custom Folding Carton Boxes for Premium Packaging",
    alt: "folding carton boxes",
  },
  {
    name: "Premium Rigid Boxes",
    description: "Premium packaging crafted from thick durable chipboard",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "rigid-boxes",
    metaTitle: "Buy Custom Rigid Boxes - Premium Packaging - Axis Packaging",
    metaDescription: "Shop rigid boxes for premium products. Custom sizes, luxury finishes, and eco-friendly packaging with fast flip turnaround.",
    h1: "Custom & Premium Rigid Boxes",
    alt: "Custom rigid box with luxury finish,Premium rigid gift boxes",
  },
  {
    name: "Custom Box Inserts",
    description: "Keep small products safe with tailored, protective box inserts",
    icon: "📋",
    image: "/assets/Custom Box Inserts.jpg",
    slug: "box-inserts",
    metaTitle: "Buy Custom Box Inserts - Premium Packaging - Axis Packaging",
    metaDescription: "Get custom box inserts for gifts and retail. Durable, stylish and versatile packaging solutions with rapid turnaround.",
    h1: "Custom & Premium Box Inserts for Packaging",
    alt: "Custom box inserts,Premium packaging inserts",
  },
  {
    name: "Custom Reusable Bags",
    description: "Say goodbye to plastic, carry reusable bags proudly",
    icon: "👜",
    image: "/assets/packify-retail-packaging.png",
    slug: "reusable-bags",
    metaTitle: "Buy Custom Reusable Bags - Top Durable & Shopping Bags",
    metaDescription: "Looking for sustainable packaging? Our custom reusable bags offer strength, style, and sustainability. Ideal for retail, grocery, and promotions.",
    h1: "Custom & Eco-Friendly Reusable Bags",
    alt: "custom reusable bags,",
  },
  {
    name: "Printed Mailer Bags",
    description: "Eco mailer bags for shipping clothing and small retail products",
    icon: "📮",
    image: "/assets/printed mailer box.jpeg",
    slug: "mailer-bags",
    metaTitle: "Shop Plastic and Customized Mailer Bags - Axis Packaging",
    metaDescription: "Order custom mailer bags for secure shipping. Eco-friendly bags ideal for clothing and small product items, available in various colors.",
  },
  {
    name: "Flexible Packaging Pouches",
    description: "Maintain food freshness and safety using resealable packaging pouches",
    icon: "🥡",
    image: "/assets/packify-food-containers.png",
    slug: "flexible-pouches",
  },
  {
    name: "Metal Tin Containers",
    description: "Searching for packaging that protects and stands out from competitors",
    icon: "🥫",
    image: "/assets/assorted-food-containers.png",
    slug: "tin-containers",
  },
  {
    name: "Retail POP Displays",
    description: "Showcase products beautifully on counters and retail store floor areas",
    icon: "🏪",
    image: "/assets/Retail POP Displays.jpg",
    slug: "pop-displays",
  },
  {
    name: "Vinyl Stickers Labels",
    description: "Add custom flair to your products and packaging for impact",
    icon: "🏷️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "stickers-labels",
  },
  {
    name: "Printed Kraft Boxes",
    description: "Showcase your products stylishly with sustainable kraft packaging",
    icon: "🌱",
    image: "/assets/Printed Kraft Boxes.jpg",
    slug: "kraft-boxes",
  },
  {
    name: "Paper Shopping Bags",
    description: "Stylish eco-friendly paper bags",
    icon: "🛍️",
    image: "/assets/retail-packaging-display.png",
    slug: "paper-bags",
  },
  {
    name: "Eco-friendly Packaging",
    description: "Sustainable alternatives to packaging",
    icon: "♻️",
    image: "/assets/packify-eco-friendly-packaging.png",
    slug: "eco-friendly",
  },
  {
    name: "Corrugated Shipping Boxes",
    description: "Heavy-duty corrugated boxes for safe shipping and storage",
    icon: "📦",
    image: "/assets/Corrugated Shipping Boxes.jpg",
    slug: "corrugated-shipping",
  },
  {
    name: "Custom Cosmetic Boxes",
    description: "Elegant packaging solutions for beauty and cosmetic products",
    icon: "💄",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "cosmetic-boxes",
  },
  {
    name: "Food Grade Containers",
    description: "FDA approved containers for food and beverage products",
    icon: "🍽️",
    image: "/assets/assorted-food-containers.png",
    slug: "food-containers",
  },
  {
    name: "Pharmaceutical Packaging",
    description: "Compliant packaging for pharmaceutical and medical products",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "pharmaceutical",
  },
  {
    name: "Electronics Packaging",
    description: "Anti-static and protective packaging for electronic devices",
    icon: "📱",
    image: "/assets/packify-electronics-packaging.png",
    slug: "electronics",
  },
  {
    name: "Jewelry Gift Boxes",
    description: "Luxury presentation boxes for jewelry and precious items",
    icon: "💍",
    image: "/assets/luxury-cosmetic-boxes.png",
    slug: "jewelry-boxes",
  },
  {
    name: "Wine & Liquor Boxes",
    description: "Premium packaging for alcoholic beverages and wine bottles",
    icon: "🍷",
    image: "/assets/packify-hero-box4.png",
    slug: "wine-boxes",
  },
  {
    name: "Bakery & Cake Boxes",
    description: "Food-safe boxes perfect for cakes, pastries, and baked goods",
    icon: "🎂",
    image: "/assets/packify-food-packaging.png",
    slug: "bakery-boxes",
  },
  {
    name: "Apparel Packaging",
    description: "Stylish boxes and bags for clothing and fashion items",
    icon: "👕",
    image: "/assets/packify-fashion-packaging.png",
    slug: "apparel-packaging",
  },
  {
    name: "Subscription Boxes",
    description: "Custom branded boxes for subscription and e-commerce businesses",
    icon: "📮",
    image: "/assets/custom-packaging-boxes.png",
    slug: "subscription-boxes",
  },
  {
    name: "Gift Wrapping Boxes",
    description: "Beautiful presentation boxes for gifts and special occasions",
    icon: "🎁",
    image: "/assets/custom-blue-box.png",
    slug: "gift-boxes",
  },
  {
    name: "Toy Packaging",
    description: "Safe and colorful packaging solutions for toys and games",
    icon: "🧸",
    image: "/assets/packify-hero-box3.png",
    slug: "toy-packaging",
    metaTitle: "Buy Toy Packaging Boxes & Custom Designs - Axis Packaging",
    metaDescription: "Shop premium toy packaging for kids, girls, and collectibles. Custom, durable, and eco-friendly boxes perfect for retail.",
    h1: "Premium Toy Packaging Boxes",
  },
  {
    name: "Book & Media Packaging",
    description: "Protective packaging for books, CDs, DVDs, and media products",
    icon: "📚",
    image: "/assets/Book & Media Packaging.jpg",
    slug: "media-packaging",
    metaTitle: "Buy Media & Book Packaging Solutions - Axis Packaging",
    metaDescription: "Protect and present CDs, DVDs, and books with our premium packaging. Custom designs, sturdy materials, perfect for retail and shipping.",
    h1: "Premium Media & Book Packaging for Retail & Shipping",
  },
  {
    name: "Automotive Parts Boxes",
    description: "Durable packaging for automotive parts and accessories",
    icon: "🚗",
    image: "/assets/Automotive Parts Boxes.jpg",
    slug: "automotive-boxes",
    metaTitle: "Buy Automotive Packaging Boxes for Parts - Axis Packaging",
    metaDescription: "Premium auto parts with durable custom automotive packaging boxes. Custom designs, foam protection, and bulk supply options.",
    h1: "Custom Auto Packaging Boxes for Secure Part Protection",
  },
  {
    name: "Sports Equipment Boxes",
    description: "Robust packaging for sports gear and equipment",
    icon: "⚽",
    image: "/assets/spports.jpg",
    slug: "sports-boxes",
    metaTitle: "Buy Custom Sports Packaging Boxes - Axis Packaging",
    metaDescription: "Design your unique custom sports packaging to reflect your brand image, protect equipment, and boost product appeal.",
    h1: "Custom Sports Packaging Boxes for Gear & Brand Impact",
  },
  {
    name: "Pet Product Packaging",
    description: "Specialized packaging for pet food, toys, and accessories",
    icon: "🐾",
    image: "/assets/assorted-food-containers.png",
    slug: "pet-packaging",
    metaTitle: "Pet Products Packaging - Custom Solutions - Axis Packaging",
    metaDescription: "Shop premium PET, custom pet packaging boxes with premium finishes and sustainable options for pet products and toys.",
    h1: "Custom PET Packaging Boxes",
  },
  {
    name: "Hardware & Tools Boxes",
    description: "Heavy-duty packaging for tools and hardware items",
    icon: "🔧",
    image: "/assets/Hardware & Tools Boxes.png",
    slug: "hardware-boxes",
    metaTitle: "Buy Hardware & Tool Boxes - Storage Solutions - Axis Packaging",
    metaDescription: "Organize, protect and store tools with hardware and tool boxes. Custom, durable, and versatile storage solutions.",
    h1: "Custom Hardware & Tool Boxes for Storage and organization",
  },
  {
    name: "Candle & Fragrance Boxes",
    description: "Elegant packaging for candles, perfumes, and fragrance products",
    icon: "🕯️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "candle-boxes",
  },
  {
    name: "Supplement Bottles",
    description: "Compliant packaging for vitamins and dietary supplements",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "supplement-bottles",
    metaTitle: "Buy Custom Supplement Bottles - Customized - Axis Packaging",
    metaDescription: "Bulk packaging, high quality, supplement bottles with customizable labels, designs, and packaging ideal for brands.",
    h1: "Custom Supplement Bottles",
  },
  {
    name: "Craft & Hobby Boxes",
    description: "Organized storage solutions for craft supplies and hobbies",
    icon: "🎨",
    image: "/assets/Craft & Hobby Boxes.jpg",
    slug: "craft-boxes",
    metaTitle: "Buy Craft and Hobby Boxes - Custom Creation - Axis Packaging",
    metaDescription: "Craft and hobby boxes designed for art supplies, DIY kits, and creative storage. Sturdy, small packaging that keeps you organized.",
    h1: "Craft and Hobby Boxes for Creative Storage and DIY Kits",
  },
  {
    name: "Garden & Plant Packaging",
    description: "Eco-friendly packaging for plants, seeds, and garden supplies",
    icon: "🌱",
    image: "/assets/packify-eco-friendly-packaging.png",
    slug: "garden-packaging",
    metaTitle: "Garden & Plant Packaging - Premium Creation - Axis Packaging",
    metaDescription: "Shop garden and plant packaging including plant boxes. Foam packaging, eco-friendly in card/kraft boxes. Perfect for gifts.",
    h1: "Custom & Plant Packaging — Plant Boxes and Plastic Packaging",
  },
  {
    name: "Office Supply Boxes",
    description: "Professional packaging for office and business supplies",
    icon: "📎",
    image: "/assets/packify-retail-boxes.png",
    slug: "office-boxes",
    metaTitle: "Shop Office Supply Boxes - Custom & Premium - Axis Packaging",
    metaDescription: "Shop office supply boxes for storage and organization, available in small, large, paper or cardboard designs for brands.",
    h1: "Office Supply Boxes — Storage and Organization Solutions",
  },
  {
    name: "Home Decor Packaging",
    description: "Protective packaging for home decoration and furniture items",
    icon: "🏠",
    image: "/assets/packify-custom-boxes.png",
    slug: "home-decor",
    metaTitle: "Buy Home Decor Packaging - Premium Creation - Axis Packaging",
    metaDescription: "Shop home decor packaging including decorative boxes, storage solutions, and subscription boxes. Perfect for gifts and collectibles.",
    h1: "Home Decor Packaging — Decoration & Storage Boxes",
  },
  {
    name: "Musical Instrument Cases",
    description: "Protective cases and packaging for musical instruments",
    icon: "🎵",
    image: "/assets/Musical Instrument Cases.jpg",
    slug: "music-cases",
  },
  {
    name: "Art & Collectibles Boxes",
    description: "Museum-quality packaging for artwork and collectible items",
    icon: "🖼️",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "art-boxes",
    metaTitle: "Shop Art & Craft Boxes - Premium Kits - Axis Packaging",
    metaDescription: "Shop art and craft boxes for storage, kits, and creative projects. Durable, organized, and premium boxes perfect for art.",
    h1: "Art & Craft Boxes — Storage and Creative Kits",
  },
];

export const TRUST_INDICATORS = [
  { text: "10+ Years Experience", icon: "⭐" },
  { text: "ISO 9001 Certified", icon: "🏆" },
  { text: "24/7 Customer Support", icon: "📞" },
  { text: "Free Design Consultation", icon: "🎨" },
];

export const INDUSTRIES = [
  {
    name: "Apparel",
    description: "Pair your apparel with one-of-a-kind custom printed clothing boxes",
    icon: "👕",
    image: "/assets/packify-fashion-packaging.png",
    slug: "apparel",
  },
  {
    name: "Bakery & Cake",
    description: "Show off your baked good with personalized cake and bakery boxes",
    icon: "🍰",
    image: "/assets/packify-food-packaging.png",
    slug: "bakery-cake",
  },
  {
    name: "Beer & Liquor",
    description: "Premium packaging for alcoholic beverages",
    icon: "🍺",
    image: "/assets/custom-blue-box.png",
    slug: "beer-liquor",
  },
  {
    name: "Beverage",
    description: "Custom packaging for all types of beverages",
    icon: "🥤",
    image: "/assets/packify-food-containers.png",
    slug: "beverage",
  },
  {
    name: "Candle",
    description: "Elegant packaging for candle products",
    icon: "🕯️",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "candle",
  },
  {
    name: "Candy & Sweets",
    description: "Sweet packaging solutions for confectionery",
    icon: "🍬",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "candy-sweets",
  },
  {
    name: "Cannabis",
    description: "Custom-crafted tamper proof marijuana packaging",
    icon: "🌿",
    image: "/assets/packify-cannabis-packaging.png",
    slug: "cannabis",
  },
  {
    name: "Chocolate",
    description: "Premium custom chocolate boxes and packaging",
    icon: "🍫",
    image: "/assets/packify-chocolate-packaging.png",
    slug: "chocolate",
  },
  {
    name: "Coffee",
    description: "Packaging solutions for coffee products",
    icon: "☕",
    image: "/assets/packify-food-containers.png",
    slug: "coffee",
  },
  {
    name: "Cosmetics",
    description: "Custom printed cosmetic boxes and packaging",
    icon: "💄",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "cosmetics",
  },
  {
    name: "E-Commerce",
    description: "Packaging solutions for online businesses",
    icon: "🛒",
    image: "/assets/e-commerce.jpg",
    slug: "ecommerce",
  },
  {
    name: "Electronics",
    description: "Protective packaging for electronic devices",
    icon: "📱",
    image: "/assets/packify-electronics-packaging.png",
    slug: "electronics",
  },
  {
    name: "Food",
    description: "Safe and compliant food packaging solutions",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "food",
  },
  {
    name: "Gift",
    description: "Beautiful packaging for gift items",
    icon: "🎁",
    image: "/assets/packify-luxury-boxes.png",
    slug: "gift",
  },
  {
    name: "Jewelry",
    description: "Luxury packaging for jewelry and accessories",
    icon: "💍",
    image: "/assets/luxury-cosmetic-boxes.png",
    slug: "jewelry",
  },
  {
    name: "Pets",
    description: "Packaging for pet products and supplies",
    icon: "🐾",
    image: "/assets/assorted-food-containers.png",
    slug: "pets",
  },
  {
    name: "Pharmaceutical",
    description: "Compliant packaging for pharmaceutical products",
    icon: "💊",
    image: "/assets/packify-pharmaceutical.png",
    slug: "pharmaceutical",
  },
  {
    name: "Presentation",
    description: "Professional presentation packaging",
    icon: "📊",
    image: "/assets/packify-retail-boxes.png",
    slug: "presentation",
  },
  {
    name: "Restaurant",
    description: "Packaging for restaurant and food service",
    icon: "🍽️",
    image: "/assets/packify-food-packaging.png",
    slug: "restaurant",
  },
  {
    name: "Retail",
    description: "Eye-catching retail displays and packaging",
    icon: "🏪",
    image: "/assets/packify-retail-packaging.png",
    slug: "retail",
  },
  {
    name: "Shipping",
    description: "Secure shipping and mailer solutions",
    icon: "📦",
    image: "/assets/packify-shipping-boxes.png",
    slug: "shipping",
  },
  {
    name: "Soap",
    description: "Packaging for soap and personal care products",
    icon: "🧼",
    image: "/assets/packify-cosmetics-packaging.png",
    slug: "soap",
  },
  {
    name: "Toy",
    description: "Fun and safe packaging for toys",
    icon: "🧸",
    image: "/assets/packify-retail-boxes.png",
    slug: "toy",
  },
  {
    name: "Tea",
    description: "Elegant packaging for tea products",
    icon: "🫖",
    image: "/assets/packify-food-containers.png",
    slug: "tea",
  },
  {
    name: "Wine",
    description: "Premium packaging for wine and spirits",
    icon: "🍷",
    image: "/assets/custom-blue-box.png",
    slug: "wine",
  },
];

export const CORRUGATED_STYLES = [
  {
    name: "Single Wall Corrugated",
    description: "Standard corrugated boxes with one layer of fluting",
    image: "/assets/packify-corrugated-boxes.png",
    slug: "single-wall",
  },
  {
    name: "Double Wall Corrugated",
    description: "Heavy-duty boxes with two layers of fluting for extra strength",
    image: "/assets/packify-custom-boxes.png",
    slug: "double-wall",
  },
  {
    name: "Triple Wall Corrugated",
    description: "Maximum strength boxes with three layers of fluting",
    image: "/assets/packify-shipping-boxes.png",
    slug: "triple-wall",
  },
  {
    name: "Die Cut Corrugated",
    description: "Custom shaped corrugated boxes for unique packaging needs",
    image: "/assets/packify-display-boxes.png",
    slug: "die-cut",
  },
];

export const CORRUGATED_OPTIONS = [
  {
    name: "E-Flute",
    description: "Thin, smooth surface perfect for printing",
    image: "/assets/packify-custom-boxes.png",
    slug: "e-flute",
  },
  {
    name: "B-Flute",
    description: "Good cushioning and compression resistance",
    image: "/assets/packify-corrugated-boxes.png",
    slug: "b-flute",
  },
  {
    name: "C-Flute",
    description: "Most common, excellent all-around performance",
    image: "/assets/packify-shipping-boxes.png",
    slug: "c-flute",
  },
  {
    name: "BC-Flute",
    description: "Double wall combination for maximum strength",
    image: "/assets/packify-custom-boxes.png",
    slug: "bc-flute",
  },
];

export const CORRUGATED_INSPIRATIONS = [
  {
    name: "Retail Display Boxes",
    description: "Eye-catching displays for retail environments",
    image: "/assets/packify-display-boxes.png",
    slug: "retail-displays",
  },
  {
    name: "Shipping Solutions",
    description: "Durable shipping boxes for e-commerce",
    image: "/assets/packify-shipping-boxes.png",
    slug: "shipping-solutions",
  },
  {
    name: "Product Packaging",
    description: "Custom product packaging with branding",
    image: "/assets/packify-custom-boxes.png",
    slug: "product-packaging",
  },
  {
    name: "Point of Purchase",
    description: "POP displays for in-store marketing",
    image: "/assets/packify-display-packaging.png",
    slug: "pop-displays",
  },
];

export const PACKAGING_SERVICES = [
  {
    name: "Structural Design & Engineering",
    description: "Our packaging experts design and engineer innovative structures",
    image: "/assets/packify-custom-boxes.png",
    slug: "structural-design",
  },
  {
    name: "Packaging Artwork Design",
    description: "Professional artwork design for your packaging",
    image: "/assets/packify-cosmetic-boxes.png",
    slug: "artwork-design",
  },
  {
    name: "Sample & Prototyping",
    description: "Create physical samples and 3D prototypes",
    image: "/assets/packify-custom-boxes.png",
    slug: "sampling-prototyping",
  },
  {
    name: "Quality Control",
    description: "Rigorous quality control and testing",
    image: "/assets/packify-custom-boxes.png",
    slug: "quality-control",
  },
];

export const CERTIFICATIONS = [
  "ISO 9001:2015",
  "FSC Certified",
  "FDA Approved Materials",
  "ROHS Compliant",
  "Recyclable Materials",
];
